URL index: [Home](https://zzz.bwh.harvard.edu/luna-walkthrough/) | [Data](https://zzz.bwh.harvard.edu/luna-walkthrough/data/) | [S1. File QC](https://zzz.bwh.harvard.edu/luna-walkthrough/p1/) | [S2. Signal QC](https://zzz.bwh.harvard.edu/luna-walkthrough/p2) | [S3. Staging](https://zzz.bwh.harvard.edu/luna-walkthrough/p3) | [S4. Artifacts](https://zzz.bwh.harvard.edu/luna-walkthrough/p4) | [S5. Analysis](https://zzz.bwh.harvard.edu/luna-walkthrough/p5)

Notebook index: [Index](../00_index.ipynb) | [S1. File QC](../p1/00_index.ipynb) | [S2. Signal QC](../p2/00_index.ipynb) | [S3. Staging](../p3/00_index.ipynb) | [S4. Artifacts](../p4/00_index.ipynb) | [S5. Analysis](../p5/00_index.ipynb)

---

# Step 2: signal-level QC

Walkthrough URL = [https://zzz.bwh.harvard.edu/luna-walkthrough/p2/](https://zzz.bwh.harvard.edu/luna-walkthrough/p2/)

In [1]:
import lunapi as lp
proj = lp.proj()

initiated lunapi v1.2.3 <lunapi.lunapi0.luna object at 0x1221e4ab0>

Having completed Step 1, the `harm1.lst` sample list should now describe a dataset that has consistent channel and annotation labels, consistent annotation formats (standard `.annot`) and nominally consistent units, sample rates and referencing. We can now move on to look at the contents of the EDFs:

 - to describe and handle [recordings with gaps](01_edfd.ipynb)

 - to identify likely [flat or duplicate signals](02_dupes.ipynb)

 - to generate some basic [signal summary statistics](03_stats.ipynb)

 - to spot and fix issues with [EEG polarity](04_pol.ipynb)

We'll first check the channel and annotation labels are as expected:

In [2]:
proj.sample_list( '../harm1.lst' )

read 20 individuals from ../harm1.lst

In [3]:
# luna harm1.lst -o out.db -s ' HEADERS & ANNOTS '
res = proj.proc( 'HEADERS & ANNOTS' )

___________________________________________________________________
Processing: F01 | ../work/harm1/F01.edf
 duration 03.00.30, 10830s | time 22.00.00 - 04.58.00 | date 01.01.85

 signals: 58 (of 58) selected in an EDF+D file
  Fp1 | Fp2 | AF3 | AF4 | F7 | F5 | F3 | F1
  F2 | F4 | F6 | F8 | FT7 | FC5 | FC3 | FC1
  FC2 | FC4 | FC6 | FT8 | T7 | C5 | C3 | C1
  C2 | C4 | C6 | T8 | TP7 | CP5 | CP3 | CP1
  CP2 | CP4 | CP6 | TP8 | P7 | P5 | P3 | P1
  P2 | P4 | P6 | P8 | PO3 | PO4 | O1 | O2
  AFZ | FZ | FCZ | CZ | CPZ | PZ | POz | OZ
  FPZ | EDF Annotations
  extracting 'EDF Annotations' track from EDF+
 ..................................................................
 CMD #1: HEADERS
   options: sig=*
 ..................................................................
 CMD #2: ANNOTS
   options: sig=*
  set epochs to default 30 seconds, 361 epochs
  keeping annotations based on any overlap with an unmasked region
___________________________________________________________________
Processing: F02 | ../work/harm1/F02.edf
 duration 07.10.33, 25833s | time 22.00.00 - 05.10.33 | date 01.01.85

 signals: 57 (of 57) selected in a standard EDF file
  Fp1 | Fp2 | AF3 | AF4 | F7 | F5 | F3 | F1
  F2 | F4 | F6 | F8 | FT7 | FC5 | FC3 | FC1
  FC2 | FC4 | FC6 | FT8 | T7 | C5 | C3 | C1
  C2 | C4 | C6 | T8 | TP7 | CP5 | CP3 | CP1
  CP2 | CP4 | CP6 | TP8 | P7 | P5 | P3 | P1
  P2 | P4 | P6 | P8 | PO3 | PO4 | O1 | O2
  AFZ | FZ | FCZ | CZ | CPZ | PZ | POz | OZ
  FPZ
 ..................................................................
 CMD #1: HEADERS
   options: sig=*
 ..................................................................
 CMD #2: ANNOTS
   options: sig=*
  set epochs to default 30 seconds, 861 epochs
  keeping annotations based on any overlap with an unmasked region
___________________________________________________________________
Processing: F03 | ../work/harm1/F03.edf
 duration 07.15.24, 26124s | time 22.00.00 - 05.15.24 | date 01.01.85

 signals: 57 (of 57) selected in a standard EDF file
  Fp1 | Fp2 | AF3 | AF4 | F7 | F5 | F3 | F1
  F2 | F4 | F6 | F8 | FT7 | FC5 | FC3 | FC1
  FC2 | FC4 | FC6 | FT8 | T7 | C5 | C3 | C1
  C2 | C4 | C6 | T8 | TP7 | CP5 | CP3 | CP1
  CP2 | CP4 | CP6 | TP8 | P7 | P5 | P3 | P1
  P2 | P4 | P6 | P8 | PO3 | PO4 | O1 | O2
  AFZ | FZ | FCZ | CZ | CPZ | PZ | POz | OZ
  FPZ
 ..................................................................
 CMD #1: HEADERS
   options: sig=*
 ..................................................................
 CMD #2: ANNOTS
   options: sig=*
  set epochs to default 30 seconds, 870 epochs
  keeping annotations based on any overlap with an unmasked region
___________________________________________________________________
Processing: F04 | ../work/harm1/F04.edf
 duration 07.18.42, 26322s | time 22.00.00 - 05.18.42 | date 01.01.85

 signals: 57 (of 57) selected in a standard EDF file
  Fp1 | Fp2 | AF3 | AF4 | F7 | F5 | F3 | F1
  F2 | F4 | F6 | F8 | FT7 | FC5 | FC3 | FC1
  FC2 | FC4 | FC6 | FT8 | T7 | C5 | C3 | C1
  C2 | C4 | C6 | T8 | TP7 | CP5 | CP3 | CP1
  CP2 | CP4 | CP6 | TP8 | P7 | P5 | P3 | P1
  P2 | P4 | P6 | P8 | PO3 | PO4 | O1 | O2
  AFZ | FZ | FCZ | CZ | CPZ | PZ | POz | OZ
  FPZ
 ..................................................................
 CMD #1: HEADERS
   options: sig=*
 ..................................................................
 CMD #2: ANNOTS
   options: sig=*
  set epochs to default 30 seconds, 877 epochs
  keeping annotations based on any overlap with an unmasked region
___________________________________________________________________
Processing: F05 | ../work/harm1/F05.edf
 duration 07.28.26, 26906s | time 22.00.00 - 05.28.26 | date 01.01.85

 signals: 57 (of 57) selected in a standard EDF file
  Fp1 | Fp2 | AF3 | AF4 | F7 | F5 | F3 | F1
  F2 | F4 | F6 | F8 | FT7 | FC5 | FC3 | FC1
  FC2 | FC4 | FC6 | FT8 | T7 | C5 | C3 | C1
  C2 | C4 | C6 | T8 | TP7 | CP5 | CP3 | CP1
  CP2 | CP4 | CP6 | TP8 | P7 | P5 | P3 | P1
  P2 | P4 | P6 | P8 | PO3 | PO4 | O1 | O2
  AFZ | FZ | FCZ | CZ | CPZ | PZ | POz | OZ
  FPZ
 ..................................................................
 CMD #1: HEADERS
   options: sig=*
 ..................................................................
 CMD #2: ANNOTS
   options: sig=*
  set epochs to default 30 seconds, 896 epochs
  keeping annotations based on any overlap with an unmasked region
___________________________________________________________________
Processing: F06 | ../work/harm1/F06.edf
 duration 06.48.30, 24510s | time 22.00.00 - 04.48.30 | date 01.01.85

 signals: 57 (of 57) selected in a standard EDF file
  Fp1 | Fp2 | AF3 | AF4 | F7 | F5 | F3 | F1
  F2 | F4 | F6 | F8 | FT7 | FC5 | FC3 | FC1
  FC2 | FC4 | FC6 | FT8 | T7 | C5 | C3 | C1
  C2 | C4 | C6 | T8 | TP7 | CP5 | CP3 | CP1
  CP2 | CP4 | CP6 | TP8 | P7 | P5 | P3 | P1
  P2 | P4 | P6 | P8 | PO3 | PO4 | O1 | O2
  AFZ | FZ | FCZ | CZ | CPZ | PZ | POz | OZ
  FPZ
 ..................................................................
 CMD #1: HEADERS
   options: sig=*
 ..................................................................
 CMD #2: ANNOTS
   options: sig=*
  set epochs to default 30 seconds, 817 epochs
  keeping annotations based on any overlap with an unmasked region
___________________________________________________________________
Processing: F07 | ../work/harm1/F07.edf
 duration 07.52.06, 28326s | time 22.00.00 - 05.52.06 | date 01.01.85

 signals: 57 (of 57) selected in a standard EDF file
  Fp1 | Fp2 | AF3 | AF4 | F7 | F5 | F3 | F1
  F2 | F4 | F6 | F8 | FT7 | FC5 | FC3 | FC1
  FC2 | FC4 | FC6 | FT8 | T7 | C5 | C3 | C1
  C2 | C4 | C6 | T8 | TP7 | CP5 | CP3 | CP1
  CP2 | CP4 | CP6 | TP8 | P7 | P5 | P3 | P1
  P2 | P4 | P6 | P8 | PO3 | PO4 | O1 | O2
  AFZ | FZ | FCZ | CZ | CPZ | PZ | POz | OZ
  FPZ
 ..................................................................
 CMD #1: HEADERS
   options: sig=*
 ..................................................................
 CMD #2: ANNOTS
   options: sig=*
  set epochs to default 30 seconds, 944 epochs
  keeping annotations based on any overlap with an unmasked region
___________________________________________________________________
Processing: F08 | ../work/harm1/F08.edf
 duration 07.01.25, 25285s | time 22.00.00 - 05.01.25 | date 01.01.85

 signals: 57 (of 57) selected in a standard EDF file
  Fp1 | Fp2 | AF3 | AF4 | F7 | F5 | F3 | F1
  F2 | F4 | F6 | F8 | FT7 | FC5 | FC3 | FC1
  FC2 | FC4 | FC6 | FT8 | T7 | C5 | C3 | C1
  C2 | C4 | C6 | T8 | TP7 | CP5 | CP3 | CP1
  CP2 | CP4 | CP6 | TP8 | P7 | P5 | P3 | P1
  P2 | P4 | P6 | P8 | PO3 | PO4 | O1 | O2
  AFZ | FZ | FCZ | CZ | CPZ | PZ | POz | OZ
  FPZ
 ..................................................................
 CMD #1: HEADERS
   options: sig=*
 ..................................................................
 CMD #2: ANNOTS
   options: sig=*
  set epochs to default 30 seconds, 842 epochs
  keeping annotations based on any overlap with an unmasked region
___________________________________________________________________
Processing: F09 | ../work/harm1/F09.edf
 duration 06.29.53, 23393s | time 22.00.00 - 04.29.53 | date 01.01.85

 signals: 57 (of 57) selected in a standard EDF file
  Fp1 | Fp2 | AF3 | AF4 | F7 | F5 | F3 | F1
  F2 | F4 | F6 | F8 | FT7 | FC5 | FC3 | FC1
  FC2 | FC4 | FC6 | FT8 | T7 | C5 | C3 | C1
  C2 | C4 | C6 | T8 | TP7 | CP5 | CP3 | CP1
  CP2 | CP4 | CP6 | TP8 | P7 | P5 | P3 | P1
  P2 | P4 | P6 | P8 | PO3 | PO4 | O1 | O2
  AFZ | FZ | FCZ | CZ | CPZ | PZ | POz | OZ
  FPZ
 ..................................................................
 CMD #1: HEADERS
   options: sig=*
 ..................................................................
 CMD #2: ANNOTS
   options: sig=*
  set epochs to default 30 seconds, 779 epochs
  keeping annotations based on any overlap with an unmasked region
___________________________________________________________________
Processing: F10 | ../work/harm1/F10.edf
 duration 07.40.46, 27646s | time 22.00.00 - 05.46.23 | date 01.01.85

 signals: 58 (of 58) selected in an EDF+D file
  Fp1 | Fp2 | AF3 | AF4 | F7 | F5 | F3 | F1
  F2 | F4 | F6 | F8 | FT7 | FC5 | FC3 | FC1
  FC2 | FC4 | FC6 | FT8 | T7 | C5 | C3 | C1
  C2 | C4 | C6 | T8 | TP7 | CP5 | CP3 | CP1
  CP2 | CP4 | CP6 | TP8 | P7 | P5 | P3 | P1
  P2 | P4 | P6 | P8 | PO3 | PO4 | O1 | O2
  AFZ | FZ | FCZ | CZ | CPZ | PZ | POz | OZ
  FPZ | EDF Annotations
  extracting 'EDF Annotations' track from EDF+
 ..................................................................
 CMD #1: HEADERS
   options: sig=*
 ..................................................................
 CMD #2: ANNOTS
   options: sig=*
  set epochs to default 30 seconds, 921 epochs
  keeping annotations based on any overlap with an unmasked region
___________________________________________________________________
Processing: M01 | ../work/harm1/M01.edf
 duration 07.18.05, 26285s | time 22.00.00 - 05.18.05 | date 01.01.85

 signals: 57 (of 57) selected in a standard EDF file
  Fp1 | Fp2 | AF3 | AF4 | F7 | F5 | F3 | F1
  F2 | F4 | F6 | F8 | FT7 | FC5 | FC3 | FC1
  FC2 | FC4 | FC6 | FT8 | T7 | C5 | C3 | C1
  C2 | C4 | C6 | T8 | TP7 | CP5 | CP3 | CP1
  CP2 | CP4 | CP6 | TP8 | P7 | P5 | P3 | P1
  P2 | P4 | P6 | P8 | PO3 | PO4 | O1 | O2
  AFZ | FZ | FCZ | CZ | CPZ | PZ | POz | OZ
  FPZ
 ..................................................................
 CMD #1: HEADERS
   options: sig=*
 ..................................................................
 CMD #2: ANNOTS
   options: sig=*
  set epochs to default 30 seconds, 876 epochs
  keeping annotations based on any overlap with an unmasked region
___________________________________________________________________
Processing: M02 | ../work/harm1/M02.edf
 duration 07.22.43, 26563s | time 22.00.00 - 05.22.43 | date 01.01.85

 signals: 57 (of 57) selected in a standard EDF file
  Fp1 | Fp2 | AF3 | AF4 | F7 | F5 | F3 | F1
  F2 | F4 | F6 | F8 | FT7 | FC5 | FC3 | FC1
  FC2 | FC4 | FC6 | FT8 | T7 | C5 | C3 | C1
  C2 | C4 | C6 | T8 | TP7 | CP5 | CP3 | CP1
  CP2 | CP4 | CP6 | TP8 | P7 | P5 | P3 | P1
  P2 | P4 | P6 | P8 | PO3 | PO4 | O1 | O2
  AFZ | FZ | FCZ | CZ | CPZ | PZ | POz | OZ
  FPZ
 ..................................................................
 CMD #1: HEADERS
   options: sig=*
 ..................................................................
 CMD #2: ANNOTS
   options: sig=*
  set epochs to default 30 seconds, 885 epochs
  keeping annotations based on any overlap with an unmasked region
___________________________________________________________________
Processing: M03 | ../work/harm1/M03.edf
 duration 07.49.00, 28140s | time 22.00.00 - 05.49.00 | date 01.01.85

 signals: 57 (of 57) selected in a standard EDF file
  Fp1 | Fp2 | AF3 | AF4 | F7 | F5 | F1 | F2
  F6 | F8 | FT7 | FC5 | FC3 | FC1 | FC2 | FC4
  FC6 | FT8 | T7 | C5 | C1 | C2 | C6 | T8
  TP7 | CP5 | CP3 | CP1 | CP2 | CP4 | CP6 | TP8
  P7 | P5 | P1 | P2 | P6 | P8 | PO3 | PO4
  O1 | O2 | AFZ | FZ | FCZ | CZ | CPZ | PZ
  POz | OZ | FPZ | C3 | C4 | F3 | F4 | P3
  P4
 ..................................................................
 CMD #1: HEADERS
   options: sig=*
 ..................................................................
 CMD #2: ANNOTS
   options: sig=*
  set epochs to default 30 seconds, 938 epochs
  keeping annotations based on any overlap with an unmasked region
___________________________________________________________________
Processing: M04 | ../work/harm1/M04.edf
 duration 07.55.32, 28532s | time 22.00.00 - 05.55.32 | date 01.01.85

 signals: 56 (of 56) selected in a standard EDF file
  Fp1 | Fp2 | AF3 | AF4 | F7 | F5 | F3 | F1
  F2 | F4 | F6 | F8 | FT7 | FC5 | FC3 | FC1
  FC2 | FC4 | FC6 | FT8 | T7 | C5 | C3 | C1
  C2 | C4 | C6 | T8 | TP7 | CP5 | CP3 | CP1
  CP2 | CP4 | CP6 | TP8 | P7 | P5 | P3 | P1
  P2 | P4 | P6 | P8 | PO3 | PO4 | O1 | O2
  AFZ | FZ | FCZ | CPZ | PZ | POz | OZ | FPZ
 ..................................................................
 CMD #1: HEADERS
   options: sig=*
 ..................................................................
 CMD #2: ANNOTS
   options: sig=*
  set epochs to default 30 seconds, 951 epochs
  keeping annotations based on any overlap with an unmasked region
___________________________________________________________________
Processing: M05 | ../work/harm1/M05.edf
 duration 07.46.45, 28005s | time 22.00.00 - 05.46.45 | date 01.01.85

 signals: 57 (of 57) selected in a standard EDF file
  Fp1 | Fp2 | AF3 | AF4 | F7 | F5 | F3 | F1
  F2 | F4 | F6 | F8 | FT7 | FC5 | FC3 | FC1
  FC2 | FC4 | FC6 | FT8 | T7 | C5 | C3 | C1
  C2 | C4 | C6 | T8 | TP7 | CP5 | CP3 | CP1
  CP2 | CP4 | CP6 | TP8 | P7 | P5 | P3 | P1
  P2 | P4 | P6 | P8 | PO3 | PO4 | O1 | O2
  AFZ | FZ | FCZ | CZ | CPZ | PZ | POz | OZ
  FPZ
 ..................................................................
 CMD #1: HEADERS
   options: sig=*
 ..................................................................
 CMD #2: ANNOTS
   options: sig=*
  set epochs to default 30 seconds, 933 epochs
  keeping annotations based on any overlap with an unmasked region
___________________________________________________________________
Processing: M06 | ../work/harm1/M06.edf
 duration 07.36.44, 27404s | time 22.00.00 - 05.36.44 | date 01.01.85

 signals: 57 (of 57) selected in a standard EDF file
  Fp1 | Fp2 | AF3 | AF4 | F7 | F5 | F3 | F1
  F2 | F4 | F6 | F8 | FT7 | FC5 | FC3 | FC1
  FC2 | FC4 | FC6 | FT8 | T7 | C5 | C3 | C1
  C2 | C4 | C6 | T8 | TP7 | CP5 | CP3 | CP1
  CP2 | CP4 | CP6 | TP8 | P7 | P5 | P3 | P1
  P2 | P4 | P6 | P8 | PO3 | PO4 | O1 | O2
  AFZ | FZ | FCZ | CZ | CPZ | PZ | POz | OZ
  FPZ
 ..................................................................
 CMD #1: HEADERS
   options: sig=*
 ..................................................................
 CMD #2: ANNOTS
   options: sig=*
  set epochs to default 30 seconds, 913 epochs
  keeping annotations based on any overlap with an unmasked region
___________________________________________________________________
Processing: M07 | ../work/harm1/M07.edf
 duration 08.19.20, 29960s | time 22.00.00 - 06.19.20 | date 01.01.85

 signals: 57 (of 57) selected in a standard EDF file
  Fp1 | Fp2 | AF3 | AF4 | F7 | F5 | F3 | F1
  F2 | F4 | F6 | F8 | FT7 | FC5 | FC3 | FC1
  FC2 | FC4 | FC6 | FT8 | T7 | C5 | C3 | C1
  C2 | C4 | C6 | T8 | TP7 | CP5 | CP3 | CP1
  CP2 | CP4 | CP6 | TP8 | P7 | P5 | P3 | P1
  P2 | P4 | P6 | P8 | PO3 | PO4 | O1 | O2
  AFZ | FZ | FCZ | CZ | CPZ | PZ | POz | OZ
  FPZ
 ..................................................................
 CMD #1: HEADERS
   options: sig=*
 ..................................................................
 CMD #2: ANNOTS
   options: sig=*
  set epochs to default 30 seconds, 998 epochs
  keeping annotations based on any overlap with an unmasked region
___________________________________________________________________
Processing: M08 | ../work/harm1/M08.edf
 duration 08.11.00, 29460s | time 22.00.00 - 06.11.00 | date 01.01.85

 signals: 57 (of 57) selected in a standard EDF file
  Fp1 | Fp2 | AF3 | AF4 | F7 | F5 | F3 | F1
  F2 | F4 | F6 | F8 | FT7 | FC5 | FC3 | FC1
  FC2 | FC4 | FC6 | FT8 | T7 | C5 | C3 | C1
  C2 | C4 | C6 | T8 | TP7 | CP5 | CP3 | CP1
  CP2 | CP4 | CP6 | TP8 | P7 | P5 | P3 | P1
  P2 | P4 | P6 | P8 | PO3 | PO4 | O1 | O2
  AFZ | FZ | FCZ | CZ | CPZ | PZ | POz | OZ
  FPZ
 ..................................................................
 CMD #1: HEADERS
   options: sig=*
 ..................................................................
 CMD #2: ANNOTS
   options: sig=*
  set epochs to default 30 seconds, 982 epochs
  keeping annotations based on any overlap with an unmasked region
___________________________________________________________________
Processing: M09 | ../work/harm1/M09.edf
 duration 08.08.32, 29312s | time 22.00.00 - 06.08.32 | date 01.01.85

 signals: 57 (of 57) selected in a standard EDF file
  Fp1 | Fp2 | AF3 | AF4 | F7 | F5 | F3 | F1
  F2 | F4 | F6 | F8 | FT7 | FC5 | FC3 | FC1
  FC2 | FC4 | FC6 | FT8 | T7 | C5 | C3 | C1
  C2 | C4 | C6 | T8 | TP7 | CP5 | CP3 | CP1
  CP2 | CP4 | CP6 | TP8 | P7 | P5 | P3 | P1
  P2 | P4 | P6 | P8 | PO3 | PO4 | O1 | O2
  AFZ | FZ | FCZ | CZ | CPZ | PZ | POz | OZ
  FPZ
 ..................................................................
 CMD #1: HEADERS
   options: sig=*
 ..................................................................
 CMD #2: ANNOTS
   options: sig=*
  set epochs to default 30 seconds, 977 epochs
  keeping annotations based on any overlap with an unmasked region
___________________________________________________________________
Processing: M10 | ../work/harm1/M10.edf
 duration 07.25.36, 26736s | time 22.00.00 - 05.33.02 | date 01.01.85

 signals: 58 (of 58) selected in an EDF+D file
  Fp1 | Fp2 | AF3 | AF4 | F7 | F5 | F3 | F1
  F2 | F4 | F6 | F8 | FT7 | FC5 | FC3 | FC1
  FC2 | FC4 | FC6 | FT8 | T7 | C5 | C3 | C1
  C2 | C4 | C6 | T8 | TP7 | CP5 | CP3 | CP1
  CP2 | CP4 | CP6 | TP8 | P7 | P5 | P3 | P1
  P2 | P4 | P6 | P8 | PO3 | PO4 | O1 | O2
  AFZ | FZ | FCZ | CZ | CPZ | PZ | POz | OZ
  FPZ | EDF Annotations
  extracting 'EDF Annotations' track from EDF+
 ..................................................................
 CMD #1: HEADERS
   options: sig=*
 ..................................................................
 CMD #2: ANNOTS
   options: sig=*
  set epochs to default 30 seconds, 890 epochs
  keeping annotations based on any overlap with an unmasked region

We'll extract a table of unique channel/sample-rate/unit combinations present:

In [4]:
# destrat out.db +HEADERS -r CH -v SR PDIM | awk ' NR != 1 { print $2 } ' | sort | uniq -c
proj.table( 'HEADERS' , 'CH' )[[ 'CH' , 'SR', 'PDIM' ]]

       CH     SR PDIM
0     AF3  128.0   uV
1     AF3  128.0   uV
2     AF3  128.0   uV
3     AF3  128.0   uV
4     AF3  128.0   uV
...   ...    ...  ...
1134  TP8  128.0   uV
1135  TP8  128.0   uV
1136  TP8  128.0   uV
1137  TP8  128.0   uV
1138  TP8  128.0   uV

[1139 rows x 3 columns]

We can use some basic pandas functions to enumerate each type:

In [5]:
tbl = proj.table( 'HEADERS' , 'CH' )[[ 'CH' , 'SR', 'PDIM' ]]  

import pandas as pd
with pd.option_context('display.max_rows', None,):
    display( tbl.groupby(['CH','SR','PDIM']).size().reset_index(name='Count') )

     CH     SR PDIM  Count
0   AF3  128.0   uV     20
1   AF4  128.0   uV     20
2   AFZ  128.0   uV     20
3    C1  128.0   uV     20
4    C2  128.0   uV     20
5    C3  128.0   uV     20
6    C4  128.0   uV     20
7    C5  128.0   uV     20
8    C6  128.0   uV     20
9   CP1  128.0   uV     20
10  CP2  128.0   uV     20
11  CP3  128.0   uV     20
12  CP4  128.0   uV     20
13  CP5  128.0   uV     20
14  CP6  128.0   uV     20
15  CPZ  128.0   uV     20
16   CZ  128.0   uV     19
17   F1  128.0   uV     20
18   F2  128.0   uV     20
19   F3  128.0   uV     20
20   F4  128.0   uV     20
21   F5  128.0   uV     20
22   F6  128.0   uV     20
23   F7  128.0   uV     20
24   F8  128.0   uV     20
25  FC1  128.0   uV     20
26  FC2  128.0   uV     20
27  FC3  128.0   uV     20
28  FC4  128.0   uV     20
29  FC5  128.0   uV     20
30  FC6  128.0   uV     20
31  FCZ  128.0   uV     20
32  FPZ  128.0   uV     20
33  FT7  128.0   uV     20
34  FT8  128.0   uV     20
35   FZ  128.0   uV     20
36  Fp1  128.0   uV     20
37  Fp2  128.0   uV     20
38   O1  128.0   uV     20
39   O2  128.0   uV     20
40   OZ  128.0   uV     20
41   P1  128.0   uV     20
42   P2  128.0   uV     20
43   P3  128.0   uV     20
44   P4  128.0   uV     20
45   P5  128.0   uV     20
46   P6  128.0   uV     20
47   P7  128.0   uV     20
48   P8  128.0   uV     20
49  PO3  128.0   uV     20
50  PO4  128.0   uV     20
51  POz  128.0   uV     20
52   PZ  128.0   uV     20
53   T7  128.0   uV     20
54   T8  128.0   uV     20
55  TP7  128.0   uV     20
56  TP8  128.0   uV     20

We see that with one exception (CZ), all channels are seen in all individuals, with the same set of labels applied; CZ appears only in 19 of 20.

For annotations, we can confirm that all labels have been mapped:

In [6]:
# destrat out.db +ANNOTS -r ANNOT | awk ' NR != 1 { print $2 } ' | sort | uniq -c
tbl = proj.table( 'ANNOTS' , 'ANNOT' )[[ 'ANNOT' ]]  
tbl.groupby(['ANNOT']).size().reset_index(name='Count')

     ANNOT  Count
0  Arousal     10
1       N1     19
2       N2     20
3       N3     19
4        R     19
5        W     19

That is, we see six distinct annotation labels; only half the sample has `Arousal` annotations marked, but that reflects the original `v2` data, rather than an issue with the steps we've run.

We'll now move to the [next section](01_edfd.ipynb) that looks at _gapped_ EDF+D files.