URL index: [Home](https://zzz.bwh.harvard.edu/luna-walkthrough/) | [Data](https://zzz.bwh.harvard.edu/luna-walkthrough/data/) | [S1. File QC](https://zzz.bwh.harvard.edu/luna-walkthrough/p1/) | [S2. Signal QC](https://zzz.bwh.harvard.edu/luna-walkthrough/p2) | [S3. Staging](https://zzz.bwh.harvard.edu/luna-walkthrough/p3) | [S4. Artifacts](https://zzz.bwh.harvard.edu/luna-walkthrough/p4) | [S5. Analysis](https://zzz.bwh.harvard.edu/luna-walkthrough/p5)

Notebook index: [Index](../00_index.ipynb) | [S1. File QC](../p1/00_index.ipynb) | [S2. Signal QC](../p2/00_index.ipynb) | [S3. Staging](../p3/00_index.ipynb) | [S4. Artifacts](../p4/00_index.ipynb) | [S5. Analysis](../p5/00_index.ipynb)

---

# 1.1. File validation

Walkthrough URL = [https://zzz.bwh.harvard.edu/luna-walkthrough/p1/valid/](https://zzz.bwh.harvard.edu/luna-walkthrough/p1/valid/)

## Initiate lunapi

In [1]:
import lunapi as lp
proj = lp.proj()

initiated lunapi v1.2.3 <lunapi.lunapi0.luna object at 0x13188ac30>

## Build a sample list

Assuming all data are in `../work/data` we can get a list of the files as follows:

In [2]:
import os
os.listdir('../work')

['data']

Note that with the exception of the initial index, this and all other notebooks are in the `p1/` or `p2/`, etc,  folders and so we need to use `..` to point to the parent directory.

Build an initial sample list.  Based on reviewing the file extensions of the annotation files, we'll explicitly specify them (i.e. so that `build` knows how to match `file1.edf` with `file1.tsv` etc.  This should return the number of EDF files found (i.e. 20).

In [3]:
proj.build( [ '../work/data/' , '-ext=csv,annot,eannot,xml,tsv' ] )

20

Display the sample list:

In [4]:
proj.sample_list()

     ID                         EDF                        Annotations
1   F01  ../work/data//edfs/F01.edf   {../work/data//annots/F01.annot}
2   F02  ../work/data//edfs/F02.edf   {../work/data//annots/F02.annot}
3   F03  ../work/data//edfs/F03.edf   {../work/data//annots/F03.annot}
4   F04  ../work/data//edfs/F04.edf                                 {}
5   F05  ../work/data//edfs/F05.edf   {../work/data//annots/F05.annot}
6   F06  ../work/data//edfs/F06.edf   {../work/data//annots/F06.annot}
7   F07  ../work/data//edfs/F07.edf   {../work/data//annots/F07.annot}
8   F08  ../work/data//edfs/F08.edf   {../work/data//annots/F08.annot}
9   F09  ../work/data//edfs/F09.edf   {../work/data//annots/F09.annot}
10  F10  ../work/data//edfs/F10.edf   {../work/data//annots/F10.annot}
11  M01  ../work/data//edfs/M01.edf     {../work/data//annots/M01.csv}
12  M02  ../work/data//edfs/M02.edf     {../work/data//annots/M02.csv}
13  M03  ../work/data//edfs/M03.edf     {../work/data//annots/M03.tsv}
14  M04  ../work/data//edfs/M04.edf     {../work/data//annots/M04.tsv}
15  M05  ../work/data//edfs/M05.edf  {../work/data//annots/M05.eannot}
16  M06  ../work/data//edfs/M06.edf  {../work/data//annots/M06.eannot}
17  M07  ../work/data//edfs/M07.edf  {../work/data//annots/M07.eannot}
18  M08  ../work/data//edfs/M08.edf  {../work/data//annots/M08.eannot}
19  M09  ../work/data//edfs/M09.edf     {../work/data//annots/M09.xml}
20  M10  ../work/data//edfs/M10.edf     {../work/data//annots/M10.xml}

Noting that one file was mislabeled, and so it is missing in the above list.  We can rename `F04b.annot` to `F04.annot`:

In [5]:
os.rename('../work/data/annots/F04b.annot', '../work/data/annots/F04.annot')

We'll now rebuild the sample-list - this now attaches all N=20 individuals correctly:

In [6]:
proj.build( [ '../work/data/' , '-ext=csv,annot,eannot,xml,tsv' ] ) 
proj.sample_list()

     ID                         EDF                        Annotations
1   F01  ../work/data//edfs/F01.edf   {../work/data//annots/F01.annot}
2   F02  ../work/data//edfs/F02.edf   {../work/data//annots/F02.annot}
3   F03  ../work/data//edfs/F03.edf   {../work/data//annots/F03.annot}
4   F04  ../work/data//edfs/F04.edf   {../work/data//annots/F04.annot}
5   F05  ../work/data//edfs/F05.edf   {../work/data//annots/F05.annot}
6   F06  ../work/data//edfs/F06.edf   {../work/data//annots/F06.annot}
7   F07  ../work/data//edfs/F07.edf   {../work/data//annots/F07.annot}
8   F08  ../work/data//edfs/F08.edf   {../work/data//annots/F08.annot}
9   F09  ../work/data//edfs/F09.edf   {../work/data//annots/F09.annot}
10  F10  ../work/data//edfs/F10.edf   {../work/data//annots/F10.annot}
11  M01  ../work/data//edfs/M01.edf     {../work/data//annots/M01.csv}
12  M02  ../work/data//edfs/M02.edf     {../work/data//annots/M02.csv}
13  M03  ../work/data//edfs/M03.edf     {../work/data//annots/M03.tsv}
14  M04  ../work/data//edfs/M04.edf     {../work/data//annots/M04.tsv}
15  M05  ../work/data//edfs/M05.edf  {../work/data//annots/M05.eannot}
16  M06  ../work/data//edfs/M06.edf  {../work/data//annots/M06.eannot}
17  M07  ../work/data//edfs/M07.edf  {../work/data//annots/M07.eannot}
18  M08  ../work/data//edfs/M08.edf  {../work/data//annots/M08.eannot}
19  M09  ../work/data//edfs/M09.edf     {../work/data//annots/M09.xml}
20  M10  ../work/data//edfs/M10.edf     {../work/data//annots/M10.xml}

## Save the sample list

To facilitate working with the other notebooks we'll save the sample list as a text file. This means we'll be able to load it easily again -- although in principle one can also easily `build()` the lunapi sample list instead, as above.  This is more to show how the various components of Luna can be used together.    

In this particular case, we'll need to strip out some special characters from the annotations field (the `{` and `}` characters above (as the annotation column reflects a _set_ of annotation files, not just one).

In [7]:
sl = proj.sample_list()
sl['Annotations'] = sl['Annotations'].map( lambda x: str(x).strip('{}\'') )
sl

     ID                         EDF                      Annotations
1   F01  ../work/data//edfs/F01.edf   ../work/data//annots/F01.annot
2   F02  ../work/data//edfs/F02.edf   ../work/data//annots/F02.annot
3   F03  ../work/data//edfs/F03.edf   ../work/data//annots/F03.annot
4   F04  ../work/data//edfs/F04.edf   ../work/data//annots/F04.annot
5   F05  ../work/data//edfs/F05.edf   ../work/data//annots/F05.annot
6   F06  ../work/data//edfs/F06.edf   ../work/data//annots/F06.annot
7   F07  ../work/data//edfs/F07.edf   ../work/data//annots/F07.annot
8   F08  ../work/data//edfs/F08.edf   ../work/data//annots/F08.annot
9   F09  ../work/data//edfs/F09.edf   ../work/data//annots/F09.annot
10  F10  ../work/data//edfs/F10.edf   ../work/data//annots/F10.annot
11  M01  ../work/data//edfs/M01.edf     ../work/data//annots/M01.csv
12  M02  ../work/data//edfs/M02.edf     ../work/data//annots/M02.csv
13  M03  ../work/data//edfs/M03.edf     ../work/data//annots/M03.tsv
14  M04  ../work/data//edfs/M04.edf     ../work/data//annots/M04.tsv
15  M05  ../work/data//edfs/M05.edf  ../work/data//annots/M05.eannot
16  M06  ../work/data//edfs/M06.edf  ../work/data//annots/M06.eannot
17  M07  ../work/data//edfs/M07.edf  ../work/data//annots/M07.eannot
18  M08  ../work/data//edfs/M08.edf  ../work/data//annots/M08.eannot
19  M09  ../work/data//edfs/M09.edf     ../work/data//annots/M09.xml
20  M10  ../work/data//edfs/M10.edf     ../work/data//annots/M10.xml

Write the sample list to a file `s1.lst` in the parent folder:

In [8]:
sl.to_csv( '../s1.lst', sep="\t", index=None, header=False)

We could have achieved the same thing (building `s1.lst`) by hand, by saving a spreadsheet as a tab-delimited text file, or by using the command-line `luna --build` option, as in the primary walk-through.

## Validate sample list files

The `validate()` function has the same functionality as the command-line `--validate`

In [9]:
# luna --validate -o out.db --options slist=s1.lst
tbl = proj.validate()

problem : [] corrupt EDF: expecting 370214400 but observed 370210000 bytes: ../work/data//edfs/F06.edf
problem : [] corrupt EDF, file < header size (256 bytes): ../work/data//edfs/F08.edf
problem : [] did not recognize annotation file extension: ../work/data//annots/M01.csv
problem : [] did not recognize annotation file extension: ../work/data//annots/M02.csv
problem : [] bad format for class-inst pairing: 22:00:00
problem : [] bad format for class-inst pairing: 22:00:00

That is, it correctly flags that six studies have problems.

We see the same six files flagged as problematic as in the main walkthrough.

In [10]:
tbl.loc[ tbl.Valid == False ]

     ID                      Filename  Valid
11  F06    ../work/data//edfs/F06.edf  False
15  F08    ../work/data//edfs/F08.edf  False
22  M01  ../work/data//annots/M01.csv  False
24  M02  ../work/data//annots/M02.csv  False
26  M03  ../work/data//annots/M03.tsv  False
28  M04  ../work/data//annots/M04.tsv  False

---
Move to the [next section](02_filefix.ipynb) where we see if we can fix these issues.